#!/usr/bin/env bash

build_dir=".buildhs"

hs_source="$1"
executable="$(basename "$hs_source" .hs)"

ghc -outputdir ./${build_dir} -o ./${build_dir}/${executable} "$hs_source"

if [[ $? -eq 0 ]]; then
    echo ">>> build completed"
    echo ">>> running ${executable}"
    ./${build_dir}/${executable}
fi
