---

- name: update apt cache
  apt:
    update_cache=yes

- name: install terminator
  apt:
    state: latest
    name: terminator
  tags: terminator

- name: install command-line tools
  apt:
    state: latest
    name: ['zsh', 'git', 'fzf', 'tree', 'curl', 'wget', 'tmux', 'jq', 'pass']

- name: install ui tools
  apt:
    state: latest
    name: gnome-sushi

- name: python interpreter
  debug:
    msg: "{{ ansible_python_interpreter }}"

- name: install python tools
  apt:
    state: latest
    name: ['python3-pip', 'python3-setuptools', 'python3-virtualenv']

- name: install python virtualenv wrapper
  pip:
    state: latest
    name: ['virtualenvwrapper', 'yq']
