---

- name: install office packages
  apt:
    name: ['firefox', 'focuswriter', 'artha', 'kazam', 'screenkey', 'bzip2', 'mc', 'libreoffice', 'gufw']
    update_cache: yes
    state: latest

- name: install skype
  include_tasks: skype.yml
  tags: skype
