---

- name: install dev tool packages
  apt:
    update_cache: yes
    state: latest
    name: ['git', 'meld', 'ag', 'xclip', 'jq', 'cloc']

- name: install vim
  include_tasks: vim.yml
  tags: vim

- name: install neovim
  include_tasks: neovim.yml
  tags: neovim

- name: install vscode
  include_tasks: vscode.yml
  tags: vscode

- name: install swagger
  include_tasks: swagger.yml
  when: False

- name: install git repo cleaner
  include_tasks: git_repo_cleaner.yml
  when: False
